name    'hardening/nginx_hardening'
version '1.0.1'
source 'https://github.com/TelekomLabs/puppet-nginx-hardening'
author 'Dominik Richter'
license 'Apache License, Version 2.0'
summary 'Configures Nginx for security hardening'
description 'Configures Nginx for security hardening'
project_page 'https://github.com/TelekomLabs/puppet-nginx-hardening'

dependency 'jfryman/nginx'
